# Generated by Django 4.1.5 on 2023-01-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
